# Generated by Django 4.1 on 2022-10-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_delete_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phone', models.TextField(max_length=10)),
                ('password', models.TextField(max_length=50)),
            ],
        ),
    ]
