# Generated by Django 4.1 on 2023-02-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='Pickup',
            field=models.CharField(choices=[('Dubai Airport', 'Dubai Airport'), ('Mumbai Airport', 'Mumbai Airport'), ('Kolkata Airport', 'Kolata Airport'), ('Delhi Airport', 'Delhi Airport'), ('Ahmedabad Airport', 'Ahmedabad Airport')], default='Dubai Airport', max_length=20),
        ),
    ]
